=== namratapatil96/demo-navigation/resources/contract/raml/schemas-responses/get-international-product-200.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "mappings": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "$ref": "../schemas-common/mapping-details.schema.json#/properties/identifier"
            },
            "alternateURLs": {
              "$ref": "../schemas-common/mapping-details.schema.json#/properties/alternateURLs"
            }
          },
          "required": [
            "id",
            "alternateURLs"
          ]
        }
      ]
    },
    "pageNumber": {
      "$ref": "../schemas-common/mapping-details.schema.json#/properties/pageNumber"
    },
    "totalPages": {
      "$ref": "../schemas-common/mapping-details.schema.json#/properties/totalPages"
    },
    "pageSize": {
      "$ref": "../schemas-common/mapping-details.schema.json#/properties/pageSize"
    },
    "totalElements": {
      "$ref": "../schemas-common/mapping-details.schema.json#/properties/totalElements"
    }
  },
  "required": [
    "mappings",
    "pageNumber",
    "totalPages",
    "pageSize",
    "totalElements"
  ]
}

=== namratapatil96/demo-navigation/resources/contract/raml/examples-responses/get-international-products-200.example.json
{
  "mappings": [
    {
      "id": "P60181750",
      "alternateURLs": [
        {
          "locale": "en-GB",
          "url": "https://www.marksandspencer.com/quilted-ribbed-bed-throw/p/hbp60181750"
        },
        {
          "locale": "x-default",
          "url": "https://www.marksandspencer.com/quilted-ribbed-bed-throw/p/hbp60181750"
        },
        {
          "locale": "en-IE",
          "url": "https://www.marksandspencer.com/ie/quilted-ribbed-bed-throw/p/hbp60181750"
        }
      ]
    },
    {
      "id": "P60181031",
      "alternateURLs": [
        {
          "locale": "en-GB",
          "url": "https://www.marksandspencer.com/60-denier-cool-comfort-opaque-tights/p/clp60181031"
        },
        {
          "locale": "x-default",
          "url": "https://www.marksandspencer.com/60-denier-cool-comfort-opaque-tights/p/clp60181031"
        },
        {
          "locale": "en-IE",
          "url": "https://www.marksandspencer.com/ie/60-denier-cool-comfort-opaque-tights/p/clp60181031"
        }
      ]
    }
  ],
  "pageNumber": 0,
  "totalPages": 745,
  "pageSize": 2,
  "totalElements": 1490
}

=== namratapatil96/demo-navigation/resources/contract/raml/examples-responses/get-international-products-UK-200.example.json
{
  "mappings": [
    {
      "id": "P60199961",
      "alternateURLs": [
        {
          "locale": "en-IE",
          "url": "https://www.marksandspencer.com/ie/1-litre-large-color-conserve-shampoo/p/hbp60199961"
        }
      ]
    },
    {
      "id": "P60155767",
      "alternateURLs": [
        {
          "locale": "en-IE",
          "url": "https://www.marksandspencer.com/ie/kids-wellies-5-small-12-small-/p/clp60155767"
        },
        {
          "locale": "ar-SA",
          "url": "https://www.marksandspencer.com/sa/%D8%AD%D9%84%D9%8A%D9%81%D8%A9-%D8%A7%D9%84%D8%A3%D8%B7%D9%81%D8%A7%D9%84-5-%D8%B5%D8%BA%D9%8A%D8%B1%D8%A9---12-%D8%B5%D8%BA%D9%8A%D8%B1%D8%A9/p/P60155767.html"
        },
        {
          "locale": "en-CZ",
          "url": "https://www.marksandspencer.com/en-cz/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-PL",
          "url": "https://www.marksandspencer.com/en-pl/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "es-US",
          "url": "https://www.marksandspencer.com/es-us/botas-de-agua-infantiles-5-peque%C3%B1o-12-peque%C3%B1o/p/P60155767.html"
        },
        {
          "locale": "en-DE",
          "url": "https://www.marksandspencer.com/en-de/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-PT",
          "url": "https://www.marksandspencer.com/pt/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-HK",
          "url": "https://www.marksandspencer.com/hk/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "cs-CZ",
          "url": "https://www.marksandspencer.com/cz/d%C4%9Btsk%C3%A9-hol%C3%ADnky-5-mal%C3%A9-%E2%80%93-12-mal%C3%A9/p/P60155767.html"
        },
        {
          "locale": "en-KW",
          "url": "https://www.marksandspencer.com/kw/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-GR",
          "url": "https://www.marksandspencer.com/en-gr/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-CY",
          "url": "https://www.marksandspencer.com/cy/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "ar-KW",
          "url": "https://www.marksandspencer.com/ar-kw/%D8%AD%D9%84%D9%8A%D9%81%D8%A9-%D8%A7%D9%84%D8%A3%D8%B7%D9%81%D8%A7%D9%84-5-%D8%B5%D8%BA%D9%8A%D8%B1%D8%A9---12-%D8%B5%D8%BA%D9%8A%D8%B1%D8%A9/p/P60155767.html"
        },
        {
          "locale": "en-US",
          "url": "https://www.marksandspencer.com/us/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-AE",
          "url": "https://www.marksandspencer.com/ae/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-IL",
          "url": "https://www.marksandspencer.com/il/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-LU",
          "url": "https://www.marksandspencer.com/en-lu/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "nl-NL",
          "url": "https://www.marksandspencer.com/nl/regenlaarzen-voor-kinderen-maat-215-305/p/P60155767.html"
        },
        {
          "locale": "en-DK",
          "url": "https://www.marksandspencer.com/dk/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-HU",
          "url": "https://www.marksandspencer.com/hu/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "nl-BE",
          "url": "https://www.marksandspencer.com/nl-be/regenlaarzen-voor-kinderen-maat-215-305/p/P60155767.html"
        },
        {
          "locale": "es-ES",
          "url": "https://www.marksandspencer.com/es/botas-de-agua-infantiles-5-peque%C3%B1o-12-peque%C3%B1o/p/P60155767.html"
        },
        {
          "locale": "en-QA",
          "url": "https://www.marksandspencer.com/qa/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "fr-LU",
          "url": "https://www.marksandspencer.com/fr-lu/bottes-enfants-en-caoutchouc-du-215-au-305/p/P60155767.html"
        },
        {
          "locale": "fr-FR",
          "url": "https://www.marksandspencer.com/fr/bottes-enfants-en-caoutchouc-du-215-au-305/p/P60155767.html"
        },
        {
          "locale": "de-DE",
          "url": "https://www.marksandspencer.com/de/gummistiefel-f%C3%BCr-kinder/p/P60155767.html"
        },
        {
          "locale": "en-NL",
          "url": "https://www.marksandspencer.com/en-nl/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-JE",
          "url": "https://www.marksandspencer.com/je/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-NO",
          "url": "https://www.marksandspencer.com/no/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-RS",
          "url": "https://www.marksandspencer.com/rs/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-JP",
          "url": "https://www.marksandspencer.com/jp/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-BE",
          "url": "https://www.marksandspencer.com/en-be/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-FI",
          "url": "https://www.marksandspencer.com/fi/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-ES",
          "url": "https://www.marksandspencer.com/en-es/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "el-GR",
          "url": "https://www.marksandspencer.com/gr/%CF%80%CE%B1%CE%B9%CE%B4%CE%B9%CE%BA%CE%AD%CF%82-%CE%B3%CE%B1%CE%BB%CF%8C%CF%84%CF%83%CE%B5%CF%82-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-MY",
          "url": "https://www.marksandspencer.com/my/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-AL",
          "url": "https://www.marksandspencer.com/al/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-IT",
          "url": "https://www.marksandspencer.com/it/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-MX",
          "url": "https://www.marksandspencer.com/en-mx/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "fr-CA",
          "url": "https://www.marksandspencer.com/fr-ca/bottes-enfants-en-caoutchouc-du-215-au-305/p/P60155767.html"
        },
        {
          "locale": "fr-CH",
          "url": "https://www.marksandspencer.com/fr-ch/bottes-enfants-en-caoutchouc-du-215-au-305/p/P60155767.html"
        },
        {
          "locale": "en-AU",
          "url": "https://www.marksandspencer.com/au/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-AT",
          "url": "https://www.marksandspencer.com/en-at/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-CA",
          "url": "https://www.marksandspencer.com/ca/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "ar-AE",
          "url": "https://www.marksandspencer.com/ar-ae/%D8%AD%D9%84%D9%8A%D9%81%D8%A9-%D8%A7%D9%84%D8%A3%D8%B7%D9%81%D8%A7%D9%84-5-%D8%B5%D8%BA%D9%8A%D8%B1%D8%A9---12-%D8%B5%D8%BA%D9%8A%D8%B1%D8%A9/p/P60155767.html"
        },
        {
          "locale": "en-CH",
          "url": "https://www.marksandspencer.com/ch/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-SA",
          "url": "https://www.marksandspencer.com/en-sa/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "de-AT",
          "url": "https://www.marksandspencer.com/at/gummistiefel-f%C3%BCr-kinder/p/P60155767.html"
        },
        {
          "locale": "en-BN",
          "url": "https://www.marksandspencer.com/bn/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-FR",
          "url": "https://www.marksandspencer.com/en-fr/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-NZ",
          "url": "https://www.marksandspencer.com/nz/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "en-SE",
          "url": "https://www.marksandspencer.com/se/kids-wellies-5-small---12-small/p/P60155767.html"
        },
        {
          "locale": "fr-BE",
          "url": "https://www.marksandspencer.com/fr-be/bottes-enfants-en-caoutchouc-du-215-au-305/p/P60155767.html"
        },
        {
          "locale": "ar-QA",
          "url": "https://www.marksandspencer.com/ar-qa/%D8%AD%D9%84%D9%8A%D9%81%D8%A9-%D8%A7%D9%84%D8%A3%D8%B7%D9%81%D8%A7%D9%84-5-%D8%B5%D8%BA%D9%8A%D8%B1%D8%A9---12-%D8%B5%D8%BA%D9%8A%D8%B1%D8%A9/p/P60155767.html"
        },
        {
          "locale": "en-SG",
          "url": "https://www.marksandspencer.com/sg/kids-wellies-5-small---12-small/p/P60155767.html"
        }
      ]
    }
  ],
  "pageNumber": 15,
  "totalPages": 2559,
  "pageSize": 2,
  "totalElements": 5118
}
